### ISSUE TITLE
Sometimes incorrectly parsing output

### ISSUE THREAD

**Issue by jwarkentin** [nekuz0r/node-arp#5]
I have some code that is currently calling `getMAC()` about once a second. Every once in a while it will return 'eth0' instead of the MAC address. It doesn't happen very often compared to how often it's called, but it happens a few times a day. This is running on a Debian Linux machine, btw.

**Comment by ZackMattor** [comment]
We're hitting this problem too! No clue why it seems to be doing this. The first time i tired it returned the interface name every time, but on the second try it returns the correct mac address... If you have any insights into this let me know and i'll be happy to open a PR. We'll probably keep investigating.

**Comment by ZackMattor** [comment]
Figured it out! PR incoming ;)

**Comment by ZackMattor** [comment]
https://github.com/nekuz0r/node-arp/pull/8
